# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
dist: trusty
latex: true

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  include:
  - r: devel
  - os: osx
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
    warnings_are_errors: false
    
before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check rstanarm*tar.gz
    
after_script:
  - tar -ztvf publipha_*.tar.gz
  - echo ${NOT_CRAN}
