# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# https://github.com/mbjoseph/minimal-rstan-travis/blob/master/.travis.yml

language: r
sudo: false
cache: packages
dist: trusty
latex: true

r_github_packages:
  - jimhester/covr


addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-7
        
env:
    - PKG_TARBALL=publipha_0.0.1.tar.gz
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

jobs:
  include:
  - r: devel
  - os: osx
  - r: release
  - r: oldrel
    warnings_are_errors: false
    
before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

# install: 
#   - R -e "install.packages('rstan')"
  
script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check publipha*tar.gz
    
after_script:
  - tar -ztvf publipha*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()' 